# Generated by Django 4.2 on 2023-05-05 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='user',
        ),
    ]
